on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 2"

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - IMAGE_TAG: arm64-musl
            TARGET: aarch64-unknown-linux-musl
            OPENSSL_ARCH: linux-aarch64
            RUST_MUSL_MAKE_CONFIG: config.mak
            TOOLCHAIN: beta
          - IMAGE_TAG: amd64-musl
            TARGET: x86_64-unknown-linux-musl
            OPENSSL_ARCH: linux-x86_64
            RUST_MUSL_MAKE_CONFIG: config.mak
            TOOLCHAIN: beta
    env: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - id: set-push
        run: |
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then
            echo "::set-output name=push::true"
          else
            echo "::set-output name=push::false"
          fi
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.env.TARGET }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.env.TARGET }}-buildx-
      - name: Clean Docker cache
        if: "contains(github.event.head_commit.message, '[clean cache]')"
        continue-on-error: true
        run: |
          rm -rf /tmp/.buildx-cache
      - name: Build amd64 image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          build-args: |
            TARGET=${{ matrix.env.TARGET }}
            OPENSSL_ARCH=${{ matrix.env.OPENSSL_ARCH }}
            RUST_MUSL_MAKE_CONFIG=${{ matrix.env.RUST_MUSL_MAKE_CONFIG }}
            TOOLCHAIN=${{ matrix.env.TOOLCHAIN }}
          tags: cookiemagic/rust-musl-cross:${{ matrix.env.IMAGE_TAG }}-amd64
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          # Temp fix
          # https://github.com/docker/build-push-action/issues/252
          # https://github.com/moby/buildkit/issues/1896
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Test Docker cargo build
        run: |
          docker run --rm \
            -v "$(pwd)/tests":/home/rust/src \
            cookiemagic/rust-musl-cross:${{ matrix.env.IMAGE_TAG }}-amd64 cargo build
      - name: Push image
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push cookiemagic/rust-musl-cross:${{ matrix.env.IMAGE_TAG }}-amd64
